### ISSUE TITLE
how to handle hours per acre values of 0

### ISSUE THREAD

**Issue by carlinstarrs** [USFS-PNW/Fia_Biosum_Scripts#25]
Currently, machines with an hours per acre value of 0 are included in the mean machine time value. I suspect we should be removing these from the mean calculation since it would technically be impossible to have a machine time of 0, correct?

**Comment by jsfried** [comment]
Good heavens yes!

**Comment by carlinstarrs** [comment]
hours per acre values of 0 are now ignored when calculating the mean hours per acre for a machine
